version: '3.8'

networks:
  electric-search:
    driver: bridge

services:
  registration-center:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - electric-search

  grpc-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE: "2"
      INDEX_NAME: "video-index"
      GROUP_INDEX: "0"
      PORT: "12305"
      DOCKER_ENVIRONMENT: "true"
    ports:
      - "12305:12305"
    networks:
      - electric-search
    depends_on:
      - registration-center
    command: >
      sh -c "
      sed -i 's/127.0.0.1:2379/registration-center:2379/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2380/registration-center:2380/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2381/registration-center:2381/g' /app/init.yml &&
      /app/main
      "

  grpc-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE: "2"
      INDEX_NAME: "video-index"
      GROUP_INDEX: "1"
      PORT: "12306"
      DOCKER_ENVIRONMENT: "true"
    ports:
      - "12306:12306"
    networks:
      - electric-search
    depends_on:
      - registration-center
    command: >
      sh -c "
      sed -i 's/127.0.0.1:2379/registration-center:2379/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2380/registration-center:2380/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2381/registration-center:2381/g' /app/init.yml &&
      /app/main
      "

  grpc-3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE: "2"
      INDEX_NAME: "video-index"
      GROUP_INDEX: "1"
      PORT: "12307"
      DOCKER_ENVIRONMENT: "true"
    ports:
      - "12307:12307"
    networks:
      - electric-search
    depends_on:
      - registration-center
    command: >
      sh -c "
      sed -i 's/127.0.0.1:2379/registration-center:2379/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2380/registration-center:2380/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2381/registration-center:2381/g' /app/init.yml &&
      /app/main
      "

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE: "3"
      INDEX_NAME: "video-index"
      DOCKER_ENVIRONMENT: "true"
    ports:
      - "9000:9000"
    networks:
      - electric-search
    depends_on:
      - registration-center
      - grpc-1
      - grpc-2
      - grpc-3
    command: >
      sh -c "
      sed -i 's/127.0.0.1:2379/registration-center:2379/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2380/registration-center:2380/g' /app/init.yml &&
      sed -i 's/127.0.0.1:2381/registration-center:2381/g' /app/init.yml &&
      /app/main
      "