// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: video.proto

package infrastructure

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BiliBiliVideo struct {
	Id            string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title         string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	PostTime      int64    `protobuf:"varint,3,opt,name=PostTime,proto3" json:"PostTime,omitempty"`
	Author        string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	ViewCount     int32    `protobuf:"varint,5,opt,name=ViewCount,proto3" json:"ViewCount,omitempty"`
	LikeCount     int32    `protobuf:"varint,6,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	CoinCount     int32    `protobuf:"varint,7,opt,name=CoinCount,proto3" json:"CoinCount,omitempty"`
	FavoriteCount int32    `protobuf:"varint,8,opt,name=FavoriteCount,proto3" json:"FavoriteCount,omitempty"`
	ShareCount    int32    `protobuf:"varint,9,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	Keywords      []string `protobuf:"bytes,10,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
}

// ProtoReflect implements protoreflect.ProtoMessage.
func (m *BiliBiliVideo) ProtoReflect() protoreflect.Message {
	panic("unimplemented")
}

func (m *BiliBiliVideo) Reset()         { *m = BiliBiliVideo{} }
func (m *BiliBiliVideo) String() string { return proto.CompactTextString(m) }
func (*BiliBiliVideo) ProtoMessage()    {}
func (*BiliBiliVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}
func (m *BiliBiliVideo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BiliBiliVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BiliBiliVideo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BiliBiliVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiliBiliVideo.Merge(m, src)
}
func (m *BiliBiliVideo) XXX_Size() int {
	return m.Size()
}
func (m *BiliBiliVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_BiliBiliVideo.DiscardUnknown(m)
}

var xxx_messageInfo_BiliBiliVideo proto.InternalMessageInfo

func (m *BiliBiliVideo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BiliBiliVideo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BiliBiliVideo) GetPostTime() int64 {
	if m != nil {
		return m.PostTime
	}
	return 0
}

func (m *BiliBiliVideo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BiliBiliVideo) GetViewCount() int32 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *BiliBiliVideo) GetLikeCount() int32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *BiliBiliVideo) GetCoinCount() int32 {
	if m != nil {
		return m.CoinCount
	}
	return 0
}

func (m *BiliBiliVideo) GetFavoriteCount() int32 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *BiliBiliVideo) GetShareCount() int32 {
	if m != nil {
		return m.ShareCount
	}
	return 0
}

func (m *BiliBiliVideo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*BiliBiliVideo)(nil), "raybox.video.BiliBiliVideo")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xcb, 0x4c, 0x49,
	0xcd, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0x4a, 0xac, 0x4c, 0xca, 0xaf, 0xd0,
	0x03, 0x8b, 0x29, 0x2d, 0x65, 0xe2, 0xe2, 0x75, 0xca, 0xcc, 0xc9, 0x04, 0xe1, 0x30, 0x90, 0x88,
	0x10, 0x1f, 0x17, 0x93, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x93, 0x67, 0x8a,
	0x90, 0x08, 0x17, 0x6b, 0x48, 0x66, 0x49, 0x4e, 0xaa, 0x04, 0x13, 0x58, 0x08, 0xc2, 0x11, 0x92,
	0xe2, 0xe2, 0x08, 0xc8, 0x2f, 0x2e, 0x09, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x56, 0x60, 0xd4, 0x60,
	0x0e, 0x82, 0xf3, 0x85, 0xc4, 0xb8, 0xd8, 0x1c, 0x4b, 0x4b, 0x32, 0xf2, 0x8b, 0x24, 0x58, 0xc0,
	0x5a, 0xa0, 0x3c, 0x21, 0x19, 0x2e, 0xce, 0xb0, 0xcc, 0xd4, 0x72, 0xe7, 0xfc, 0xd2, 0xbc, 0x12,
	0x09, 0x56, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x84, 0x00, 0x48, 0xd6, 0x27, 0x33, 0x3b, 0x15, 0x22,
	0xcb, 0x06, 0x91, 0x85, 0x0b, 0x80, 0x64, 0x9d, 0xf3, 0x33, 0xf3, 0x20, 0xb2, 0xec, 0x10, 0x59,
	0xb8, 0x80, 0x90, 0x0a, 0x17, 0xaf, 0x5b, 0x62, 0x59, 0x7e, 0x51, 0x66, 0x09, 0x54, 0x3f, 0x07,
	0x58, 0x05, 0xaa, 0xa0, 0x90, 0x1c, 0x17, 0x57, 0x71, 0x46, 0x62, 0x11, 0x54, 0x09, 0x27, 0x58,
	0x09, 0x92, 0x08, 0xc8, 0x4f, 0xde, 0xa9, 0x95, 0xe5, 0xf9, 0x45, 0x29, 0xc5, 0x12, 0x5c, 0x0a,
	0xcc, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x93, 0xc2, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31,
	0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb,
	0x31, 0x44, 0xb1, 0x25, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x25, 0xb1, 0x81, 0x83, 0xd7, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x99, 0x11, 0x27, 0x93, 0x6d, 0x01, 0x00, 0x00,
}

func (m *BiliBiliVideo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BiliBiliVideo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BiliBiliVideo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Keywords) > 0 {
		for iNdEx := len(m.Keywords) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Keywords[iNdEx])
			copy(dAtA[i:], m.Keywords[iNdEx])
			i = encodeVarintVideo(dAtA, i, uint64(len(m.Keywords[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.ShareCount != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.ShareCount))
		i--
		dAtA[i] = 0x48
	}
	if m.FavoriteCount != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.FavoriteCount))
		i--
		dAtA[i] = 0x40
	}
	if m.CoinCount != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.CoinCount))
		i--
		dAtA[i] = 0x38
	}
	if m.LikeCount != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.LikeCount))
		i--
		dAtA[i] = 0x30
	}
	if m.ViewCount != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.ViewCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x22
	}
	if m.PostTime != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.PostTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVideo(dAtA []byte, offset int, v uint64) int {
	offset -= sovVideo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BiliBiliVideo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	if m.PostTime != 0 {
		n += 1 + sovVideo(uint64(m.PostTime))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	if m.ViewCount != 0 {
		n += 1 + sovVideo(uint64(m.ViewCount))
	}
	if m.LikeCount != 0 {
		n += 1 + sovVideo(uint64(m.LikeCount))
	}
	if m.CoinCount != 0 {
		n += 1 + sovVideo(uint64(m.CoinCount))
	}
	if m.FavoriteCount != 0 {
		n += 1 + sovVideo(uint64(m.FavoriteCount))
	}
	if m.ShareCount != 0 {
		n += 1 + sovVideo(uint64(m.ShareCount))
	}
	if len(m.Keywords) > 0 {
		for _, s := range m.Keywords {
			l = len(s)
			n += 1 + l + sovVideo(uint64(l))
		}
	}
	return n
}

func sovVideo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVideo(x uint64) (n int) {
	return sovVideo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BiliBiliVideo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVideo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BiliBiliVideo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BiliBiliVideo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostTime", wireType)
			}
			m.PostTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ViewCount", wireType)
			}
			m.ViewCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ViewCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LikeCount", wireType)
			}
			m.LikeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LikeCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinCount", wireType)
			}
			m.CoinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FavoriteCount", wireType)
			}
			m.FavoriteCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FavoriteCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareCount", wireType)
			}
			m.ShareCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShareCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keywords = append(m.Keywords, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVideo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVideo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVideo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVideo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVideo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVideo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVideo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVideo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVideo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVideo = fmt.Errorf("proto: unexpected end of group")
)
